import{a as w,S,i as n}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const C="50367186-ce245e32e2c7fc274bc460135",q="https://pixabay.com/api/";async function $(o,r=1){const s={key:C,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r},a=await w.get(q,{params:s});return{images:a.data.hits,totalHits:a.data.totalHits}}const g=document.querySelector(".gallery"),p=document.querySelector(".load-more"),y=document.querySelector(".loader"),h=document.querySelector(".text-loading"),B=new S(".gallery a",{captionsData:"alt",captionDelay:250});function E(o){const r=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:t,views:i,comments:v,downloads:x})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${s}" alt="${e}" title="${e}" />
        </a>
        <div class="img-container">
          <div class="stats">
            <p><strong>Likes:</strong> ${t}</p>
            <p><strong>Views:</strong> ${i}</p>
            <p><strong>Comments:</strong> ${v}</p>
            <p><strong>Downloads:</strong> ${x}</p>
          </div>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",r),B.refresh()}function H(){g.innerHTML=""}function M(){y.classList.add("is-active"),h.style.display="block"}function P(){y.classList.remove("is-active"),h.style.display="none"}function R(){p.classList.add("is-active")}function l(){p.classList.remove("is-active")}const b=document.querySelector(".form"),A=b.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let c=1,d="",f=0,u=0,m=0;b.addEventListener("submit",async o=>{if(o.preventDefault(),d=A.value.trim(),!d){n.warning({title:"Empty search",message:"Please enter a search term.",position:"topRight",backgroundColor:" #ef4040",messageColor:" #fafafb",maxWidth:"432px",timeout:3e3});return}c=1,u=0,H(),l(),await L()});O.addEventListener("click",async()=>{c+=1,await L()});async function L(){M();try{const{images:o,totalHits:r}=await $(d,c);if(f=r,o.length===0&&c===1){n.warning({title:"No results",message:"Sorry, no images found.",position:"topRight",backgroundColor:" #ef4040",messageColor:" #fafafb",maxWidth:"432px",timeout:3e3}),l();return}E(o),u+=o.length;const s=document.querySelectorAll(".gallery-item");s.length>0&&(m=s[s.length-1].getBoundingClientRect().height,window.scrollBy({top:m*2,behavior:"smooth"})),u>=f?(n.info({message:"We re sorry, but you ve reached the end of search results.",position:"topRight",backgroundColor:" #007bff",messageColor:" #fafafb",maxWidth:"432px",timeout:3e3}),l()):R()}catch{n.error({message:"Error fetching images.",position:"topRight",backgroundColor:" #ef4040",messageColor:" #fafafb",maxWidth:"432px",timeout:3e3})}finally{P()}}
//# sourceMappingURL=index.js.map
