import{a as S,S as q,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const C="50367186-ce245e32e2c7fc274bc460135",$="https://pixabay.com/api/";async function B(o,r=1){const s={key:C,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r},a=await S.get($,{params:s});return{images:a.data.hits,totalHits:a.data.totalHits}}const m=document.querySelector(".gallery"),g=document.querySelector(".load-more"),p=document.querySelector(".loader"),y=document.querySelector(".text-loading"),E=new q(".gallery a",{captionsData:"alt",captionDelay:250});function H(o){const r=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:t,views:i,comments:w,downloads:x})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${s}" alt="${e}" title="${e}" />
        </a>
        <div class="img-container">
          <div class="stats">
            <p><strong>Likes:</strong> ${t}</p>
            <p><strong>Views:</strong> ${i}</p>
            <p><strong>Comments:</strong> ${w}</p>
            <p><strong>Downloads:</strong> ${x}</p>
          </div>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",r),E.refresh()}function M(){m.innerHTML=""}function A(){p.classList.add("is-active"),y.style.display="block"}function O(){p.classList.remove("is-active"),y.style.display="none"}function h(){g.classList.add("is-active")}function d(){g.classList.remove("is-active")}const L=document.querySelector(".form"),P=L.querySelector('input[name="search-text"]'),R=document.querySelector(".load-more");let n=1,b="",u=0,l=0,f=0;L.addEventListener("submit",async o=>{o.preventDefault(),b=P.value.trim(),n=1,l=0,M(),h(),await v()});R.addEventListener("click",async()=>{n+=1,await v()});async function v(){A();try{const{images:o,totalHits:r}=await B(b,n);if(u=r,o.length===0&&n===1){c.warning({title:"No results",message:"Sorry, no images found.",position:"topRight",backgroundColor:" #ef4040",messageColor:" #fafafb",maxWidth:"432px",timeout:3e3}),d();return}H(o),l+=o.length;const s=document.querySelectorAll(".gallery-item");s.length>0&&(f=s[s.length-1].getBoundingClientRect().height,window.scrollBy({top:f*2,behavior:"smooth"})),l>=u?(c.info({message:"We re sorry, but you ve reached the end of search results.",position:"topRight",backgroundColor:" #007bff",messageColor:" #fafafb",maxWidth:"432px",timeout:3e3}),d()):h()}catch{c.error({message:"Error fetching images.",position:"topRight",backgroundColor:" #ef4040",messageColor:" #fafafb",maxWidth:"432px",timeout:3e3})}finally{O()}}
//# sourceMappingURL=index.js.map
