import{a as q,S as C,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const $="50367186-ce245e32e2c7fc274bc460135",B="https://pixabay.com/api/";async function E(o,r=1){const a={key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r},s=await q.get(B,{params:a});return{images:s.data.hits,totalHits:s.data.totalHits}}const g=document.querySelector(".gallery"),p=document.querySelector(".load-more"),y=document.querySelector(".loader"),h=document.querySelector(".text-loading"),H=new C(".gallery a",{captionsData:"alt",captionDelay:250});function M(o){const r=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:t,views:i,comments:x,downloads:S})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img src="${a}" alt="${e}" title="${e}" />
        </a>
        <div class="img-container">
          <div class="stats">
            <p><strong>Likes:</strong> ${t}</p>
            <p><strong>Views:</strong> ${i}</p>
            <p><strong>Comments:</strong> ${x}</p>
            <p><strong>Downloads:</strong> ${S}</p>
          </div>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",r),H.refresh()}function A(){g.innerHTML=""}function O(){y.classList.add("is-active"),h.style.display="block"}function P(){y.classList.remove("is-active"),h.style.display="none"}function L(){p.classList.add("is-active")}function u(){p.classList.remove("is-active")}const b=document.querySelector(".form"),R=b.querySelector('input[name="search-text"]'),D=document.querySelector(".load-more"),l=document.querySelectorAll(".gallery-item");let n=1,v="",f=0,d=0,m=0;b.addEventListener("submit",async o=>{o.preventDefault(),v=R.value.trim(),n=1,d=0,A(),L(),await w()});D.addEventListener("click",async()=>{n+=1,await w()});async function w(){O();try{const{images:o,totalHits:r}=await E(v,n);if(f=r,o.length===0&&n===1){c.warning({title:"No results",message:"Sorry, no images found.",position:"topRight",backgroundColor:" #ef4040",messageColor:" #fafafb",maxWidth:"432px",timeout:3e3}),u();return}M(o),d+=o.length,l.length>0&&(m=l[l.length-1].getBoundingClientRect().height,window.scrollBy({top:m*2,behavior:"smooth"})),d>=f?(c.info({message:"We re sorry, but you ve reached the end of search results.",position:"topRight",backgroundColor:" #007bff",messageColor:" #fafafb",maxWidth:"432px",timeout:3e3}),u()):L()}catch{c.error({message:"Error fetching images.",position:"topRight",backgroundColor:" #ef4040",messageColor:" #fafafb",maxWidth:"432px",timeout:3e3})}finally{P()}}
//# sourceMappingURL=index.js.map
